server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: policy_holder_bot
    static_configs:
      - targets: [localhost]
        labels:
          job: policy_holder_bot
          __path__: /var/log/bot.log
  
  - job_name: open_banking_api_mock
    static_configs:
      - targets: [localhost]
        labels:
          job: open_banking_api_mock
          __path__: /var/log/mock.log

  - job_name: insurer_backend
    static_configs:
      - targets: [localhost]
        labels:
          job: insurer_backend
          __path__: /var/log/insurer.log
